In [2]:
import pandas as pd
import numpy as np

In [6]:
support_tickets = pd.read_csv(r"D:\DATA_ANAlSYS\Support_tickets_automation\python_automation_support_tickets.csv")
support_tickets.head()

,ticket_id,created_at,customer_id,customer_city,channel,priority,issue_type,assigned_agent,status,first_response_mins,resolution_hours,csat_score,reopened_flag,resolved_at,sla_target_hours,sla_met_flag
0,70800,2024-11-19 23:51:00,2290,Tanta,Portal,High,Billing,ALI,Open,652.0,NaN,NaN,0,NaN,24.0,NaN
1,70459,2025-02-26 17:35:00,2433,Suez,Portal,low,REFUND,Omar,resolved,388.0,28.0,4.0,0,2025-02-27 21:35:00,72.0,1.0
2,70161,2024-11-07 18:12:00,2417,SUEZ,Email,Critical,refund,Heba,OPEN,613.0,NaN,5.0,0,NaN,8.0,NaN
3,70724,2024-11-20 07:54:00,2596,Mansoura,Email,Medium,Complaint,Heba,Pending,686.0,112.0,4.0,1,NaN,48.0,0.0
4,70792,2024-09-22 17:58:00,2508,Giza,Phone,Low,Account,NADA,Resolved,320.0,35.0,NaN,0,2024-09-24 04:58:00,72.0,1.0

In [12]:
support_tickets.sample(10)

,ticket_id,created_at,customer_id,customer_city,channel,priority,issue_type,assigned_agent,status,first_response_mins,resolution_hours,csat_score,reopened_flag,resolved_at,sla_target_hours,sla_met_flag
1319,70493,2024-10-15 17:24:00,2420,Giza,Phone,Low,Technical,Sara,RESOLVED,399.0,85.0,3.0,0,2024-10-19 06:24:00,72.0,0.0
100,70864,2024-12-07 21:13:00,2088,Alexandria,CHAT,Low,Technical,SARA,PENDING,65.0,NaN,2.0,0,NaN,72.0,NaN
1032,70679,2024-12-17 10:12:00,2303,Tanta,Email,Low,Refund,Sara,open,103.0,NaN,4.0,0,NaN,72.0,NaN
924,70366,2024-11-17 23:45:00,2257,Zagazig,Email,medium,Refund,heba,resolved,356.0,20.0,NaN,0,2024-11-18 19:45:00,48.0,1.0
1234,71034,2024-09-26 01:06:00,2495,Suez,Portal,Low,Billing,Farah,Resolved,227.0,154.0,1.0,0,2024-10-02 11:06:00,72.0,0.0
1201,70889,2024-09-26 11:17:00,2358,Ismailia,Chat,Low,Complaint,NADA,resolved,100.0,21.0,4.0,0,2024-09-27 08:17:00,72.0,1.0
269,71146,2024-10-08 21:08:00,2084,Giza,Chat,Medium,Complaint,nada,Closed,651.0,85.0,4.0,0,2024-10-12 10:08:00,48.0,0.0
452,70103,2024-09-26 06:28:00,2129,Giza,Portal,Low,BILLING,Ali,open,201.0,NaN,3.0,0,NaN,72.0,NaN
1296,71267,2024-12-30 18:50:00,2362,Alexandria,phone,Low,Delivery,Heba,Open,25.0,NaN,5.0,0,NaN,72.0,NaN
610,70335,2025-01-30 01:06:00,2228,Mansoura,Portal,High,Account,Omar,RESOLVED,534.0,62.0,4.0,0,2025-02-01 15:06:00,24.0,0.0

In [20]:
support_tickets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1616 entries, 0 to 1615
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ticket_id            1616 non-null   int64
 1   created_at           1616 non-null   datetime64[ns]
 2   customer_id          1616 non-null   int64
 3   customer_city        1583 non-null   object
 4   channel              1616 non-null   object
 5   priority             1616 non-null   object
 6   issue_type           1616 non-null   object
 7   assigned_agent       1592 non-null   object
 8   status               1616 non-null   object
 9   first_response_mins  1616 non-null   float64
 10  resolution_hours     1314 non-null   float64
 11  csat_score           1290 non-null   float64
 12  reopened_flag        1616 non-null   int64
 13  resolved_at          1108 non-null   datetime64[ns]
 14  sla_target_hours     1616 non-null   float64
 15  sla_met_flag         1314 non-null   float64
dtypes: datetime64[ns](2), float64(5), int64(3), object(6)
memory usage: 202.1+ KB

In [14]:
support_tickets.describe()

,ticket_id,customer_id,first_response_mins,resolution_hours,csat_score,reopened_flag,sla_target_hours,sla_met_flag
count,1616.000000,1616.000000,1616.000000,1314.000000,1290.000000,1616.000000,1616.000000,1314.000000
mean,70799.077351,2295.457302,359.281559,83.008371,3.823256,0.102104,49.470297,0.248097
std,461.079651,172.774656,210.228248,48.642587,1.133352,0.302879,20.563374,0.432073
min,70001.000000,2001.000000,-5.000000,-2.000000,1.000000,0.000000,8.000000,0.000000
25%,70400.750000,2145.750000,180.750000,41.000000,3.000000,0.000000,24.000000,0.000000
50%,70797.500000,2289.000000,359.000000,81.500000,4.000000,0.000000,48.000000,0.000000
75%,71197.250000,2445.000000,542.250000,125.000000,5.000000,0.000000,72.000000,0.000000
max,71600.000000,2599.000000,719.000000,167.000000,5.000000,1.000000,72.000000,1.000000

In [16]:
support_tickets.duplicated().sum()

16

In [29]:
support_tickets.isna().sum().sum()

1108

In [30]:
support_tickets.isna().sum().sort_values(ascending=False)

resolved_at            504
resolution_hours       302
sla_met_flag           302
ticket_id                0
created_at               0
customer_id              0
customer_city            0
channel                  0
priority                 0
issue_type               0
assigned_agent           0
status                   0
first_response_mins      0
csat_score               0
reopened_flag            0
sla_target_hours         0
dtype: int64

In [19]:
support_tickets['created_at'] = pd.to_datetime(support_tickets['created_at'], errors='coerce')
support_tickets['resolved_at'] = pd.to_datetime(support_tickets['resolved_at'], errors='coerce')

In [22]:
numeric_columns = ["first_response_mins", "resolution_hours", "csat_score", "sla_target_hours", "sla_met_flag"]
for col in numeric_columns:
    support_tickets[col] = pd.to_numeric(support_tickets[col], errors='coerce')

In [23]:
text_columns = ["customer_city", "channel", "priority", "issue_type", "assigned_agent", "status"]

def clean_text_cols(value):
    if pd.isna(value):
        return value
    return str(value).strip().title()



for col in text_columns:
    support_tickets[col] = support_tickets[col].apply(clean_text_cols)

In [25]:
support_tickets["customer_city"].unique()

array(['Tanta', 'Suez', 'Mansoura', 'Giza', 'Zagazig', 'Alexandria',
       'Ismailia', 'Cairo', nan], dtype=object)

In [26]:
support_tickets.drop_duplicates(inplace=True)

In [27]:
support_tickets.duplicated().sum()

0

In [28]:
support_tickets['customer_city']= support_tickets['customer_city'].fillna('Unknown')
support_tickets['assigned_agent'] = support_tickets['assigned_agent'].fillna('Unassigned')
support_tickets['csat_score'] = support_tickets['csat_score'].fillna(support_tickets['csat_score'].median())

In [31]:
support_tickets.loc[support_tickets["first_response_mins"] < 0, "first_response_mins"] = np.nan
support_tickets.loc[support_tickets["resolution_hours"] < 0, "resolution_hours"] = np.nan

In [32]:
sla_map={
    "Low": 72,
    "Medium": 48,
    "High": 24,
    "Critical": 8
}
support_tickets['sla_target_hours'] = support_tickets['priority'].map(sla_map)

In [33]:
support_tickets.head(10)

,ticket_id,created_at,customer_id,customer_city,channel,priority,issue_type,assigned_agent,status,first_response_mins,resolution_hours,csat_score,reopened_flag,resolved_at,sla_target_hours,sla_met_flag
0,70800,2024-11-19 23:51:00,2290,Tanta,Portal,High,Billing,Ali,Open,652.0,NaN,4.0,0,NaT,24,NaN
1,70459,2025-02-26 17:35:00,2433,Suez,Portal,Low,Refund,Omar,Resolved,388.0,28.0,4.0,0,2025-02-27 21:35:00,72,1.0
2,70161,2024-11-07 18:12:00,2417,Suez,Email,Critical,Refund,Heba,Open,613.0,NaN,5.0,0,NaT,8,NaN
3,70724,2024-11-20 07:54:00,2596,Mansoura,Email,Medium,Complaint,Heba,Pending,686.0,112.0,4.0,1,NaT,48,0.0
4,70792,2024-09-22 17:58:00,2508,Giza,Phone,Low,Account,Nada,Resolved,320.0,35.0,4.0,0,2024-09-24 04:58:00,72,1.0
5,70611,2024-11-10 05:53:00,2295,Zagazig,Email,Medium,Refund,Farah,Resolved,228.0,51.0,1.0,0,2024-11-12 08:53:00,48,0.0
6,70869,2025-01-02 16:03:00,2177,Suez,Email,Medium,Refund,Mina,Resolved,468.0,19.0,1.0,0,2025-01-03 11:03:00,48,1.0
7,71284,2024-11-10 22:16:00,2306,Tanta,Portal,Medium,Delivery,Mina,Resolved,480.0,12.0,4.0,0,2024-11-11 10:16:00,48,1.0
8,70925,2024-12-07 02:06:00,2527,Zagazig,Phone,Low,Account,Youssef,Pending,274.0,73.0,3.0,0,NaT,72,0.0
9,71093,2024-10-28 20:43:00,2211,Suez,Email,High,Delivery,Farah,Resolved,307.0,29.0,4.0,0,2024-10-30 01:43:00,24,0.0

In [34]:
support_tickets['sla_met_flag'] = np.where(
    (support_tickets['resolved_at'].notna()) & (support_tickets['resolution_hours'].notna()), 
    (support_tickets['resolution_hours'] <= support_tickets['sla_target_hours']).astype(int), np.nan)

In [35]:
support_tickets["Month Name"] = support_tickets["created_at"].dt.month_name()
support_tickets["Day of Week"] = support_tickets["created_at"].dt.day_name()
support_tickets.head()

,ticket_id,created_at,customer_id,customer_city,channel,priority,issue_type,assigned_agent,status,first_response_mins,resolution_hours,csat_score,reopened_flag,resolved_at,sla_target_hours,sla_met_flag,Month Name,Day of Week
0,70800,2024-11-19 23:51:00,2290,Tanta,Portal,High,Billing,Ali,Open,652.0,NaN,4.0,0,NaT,24,NaN,November,Tuesday
1,70459,2025-02-26 17:35:00,2433,Suez,Portal,Low,Refund,Omar,Resolved,388.0,28.0,4.0,0,2025-02-27 21:35:00,72,1.0,February,Wednesday
2,70161,2024-11-07 18:12:00,2417,Suez,Email,Critical,Refund,Heba,Open,613.0,NaN,5.0,0,NaT,8,NaN,November,Thursday
3,70724,2024-11-20 07:54:00,2596,Mansoura,Email,Medium,Complaint,Heba,Pending,686.0,112.0,4.0,1,NaT,48,NaN,November,Wednesday
4,70792,2024-09-22 17:58:00,2508,Giza,Phone,Low,Account,Nada,Resolved,320.0,35.0,4.0,0,2024-09-24 04:58:00,72,1.0,September,Sunday

In [37]:
support_tickets.to_csv(r"D:\DATA_ANAlSYS\Support_tickets_automation\cleaned_support_tickets.csv", index=False)